### ISSUE TITLE
Where do I ask questions about specific setup's?

### ISSUE THREAD

**Issue by pjdevries** [osteel/docker-tutorial#11]
Hi @osteel. Let me first thank you for this Docker tutorial. I am using it for over a year now for my local development, but never got around to make an attempt to getting to know it. This tutorial series is an excellent starting point.

I have a specific setup I still don't know how to setup. I am also somewhat of a paranoia dinosaur and don't use social media. You either have no e-mail or prefer not to share the address with the public, understandably so. So my question is if you are available for advice in specific situations and if so, where do I ask my questions?

**Comment by osteel** [comment]
Hi Pieter-Jan,

So my "policy" is usually to provide assistance within the scope of my articles only. If you've got an issue with one of my tutorials, you can leave a comment at the end of the post and I'll try to help the best I can. Anything beyond that scope is, well, beyond scope and it then becomes more like free consulting, which I could potentially provide on a case-by-case basis and when I happen to have some spare time, which unfortunately I don't have at the moment.

Thanks for your understanding and good luck!

Cheers,

Yannick
