### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by viethc** [osteel/docker-tutorial#4]
Hi there,

I received a proxy error like this:
`Proxy error: Could not proxy request /api/login from frontend.demo.test to http://backend.demo.test/.
frontend_1    | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).`

Help me, please. Thanks!

**Comment by osteel** [comment]
Hi,

Which part of the series is this? Part 3? Also, what's your setup? Docker for Mac, Windows (WSL 2?), or Linux?

**Comment by viethc** [comment]
Thanks for your feedback,


> Hi,
> 
> Which part of the series is this? Part 3? Also, what's your setup? Docker for Mac, Windows (WSL 2?), or Linux?

Yes, part 3 and I using Docker for Mac (10.14.6)
Is there a problem with the installation environment?

**Comment by osteel** [comment]
> Is there a problem with the installation environment?

Not necessarily, I was just eliminating potential sources for the issue :)

I'm not sure where you got this error from (browser? Command line?), but I've done a clean install of part 3 and realised some instructions were missing from [the repository's README](https://github.com/osteel/docker-tutorial/tree/part-3).

I have now updated them, so my advice would be that you try a clean install too. It'd be better to clean up the previous install first, to avoid any conflicts. From the root of your current install of part 3:

```
$ docker-compose down -v --rmi all
```

Once that's done, please try a clean install of part 3 somewhere else on your computer, following [the instructions](https://github.com/osteel/docker-tutorial/tree/part-3). Let me know if you still have the same issue then, and we'll take it from there if that's the case.

Also, remember that when you do `docker-compose up -d`, under the hood Yarn starts the development server for the frontend application, which can take a while. After running `docker-compose up -d`, you can monitor what the frontend container is doing with the following command:

```
$ docker-compose logs -f frontend
```

You'll then see when the frontend is actually ready (`ctrl + c` to exit the logs).

**Comment by viethc** [comment]
Hi,
Thanks so much for your support.
I found my problem.
The cause of the error is that I have installed the proxy config in the `vue.config.js` file
I deleted this config.
