### ISSUE TITLE
phpmyadmin.test doesnt seem to work with https...

### ISSUE THREAD

**Issue by shinzoke** [osteel/docker-tutorial#5]
I came across the error right after we installed the certificates... 
when i entered phpmyadmin.test it was showing up as not secured.

changed the server_name to phpmyadmin.demo.test and restarted the container...

Works like it should work now :)

hope this helps out some others

**Comment by osteel** [comment]
Nice catch! The domain name should be changed from `phpmyadmin.test` to `phpmyadmin.demo.test` starting from part 3. Will update the articles and repository when I get the chance

**Comment by shinzoke** [comment]
created a pull-request for it ;)

**Comment by osteel** [comment]
@shinzoke thanks! Could you also update the URLs in the `README.md` file at the root?

If you do this I then should be able to merge your PRs and cherry-pick the corresponding commits onto the other branches :)

**Comment by shinzoke** [comment]
@osteel done! :)

**Comment by osteel** [comment]
@shinzoke thanks, but you missed a few I'm afraid, and I'd rather it's done in as few PRs as possible :)

Don't spend too much time on this honestly, I appreciate you wanting to help but truth is it'll probably be quicker for me to do it myself. I'll do it in one commit on part-3 that I will then cherry-pick onto the rest of the branches

I'm planning to do it this Saturday, just a bit busy this week

**Comment by shinzoke** [comment]
@osteel ah ok :) 
np, i'm kinda "new" to the whole github thingy and contributing to others repo's. 
But thanks for the appreciation 👍

**Comment by osteel** [comment]
@shinzoke no worries! I certainly don't want to discourage you from contributing – by all means keep exploring 😉

**Comment by osteel** [comment]
@shinzoke I have now updated the domain name throughout the branches. Thanks again!
