### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by bckelley** [osteel/docker-tutorial#9]
following your first part of this tut iget this error, when adding mysql:

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by osteel** [comment]
Hi, looks like you need to update your Docker Compose. Are you using Docker Desktop (Windows or Mac) or are you on a Linux distribution?

**Comment by bckelley** [comment]
it's WSL2

Docker version 20.10.14, build a224086
docker-compose version 1.25.0, build unknown

**Comment by bckelley** [comment]
any ideas on getting it to upgrade?

**Comment by osteel** [comment]
Ok so WSL 2 is still Docker Desktop as far as I'm aware (I'm a macOS user), so if Docker doesn't suggest an update like on the screenshot below, just try and download the latest version from the [website](https://docs.docker.com/desktop/windows/wsl/)?

<img width="266" alt="Screenshot 2022-04-26 at 09 12 23" src="https://user-images.githubusercontent.com/436467/165253701-4ff97bb9-b5d5-48ca-8707-6bbccb3aac89.png">

**Comment by bckelley** [comment]
nope not anymore apparently, I don't have Docker Desktop on my machine

**Comment by osteel** [comment]
How did you install Docker and Docker Compose in the first place?

**Comment by bckelley** [comment]
WSL2 it's already installed

**Comment by osteel** [comment]
WSL2 isn't Docker though. Please follow the steps listed [here](https://docs.docker.com/desktop/windows/wsl/) and see where you get to

**Comment by bckelley** [comment]
you don't believe me: this is my wsl bash instances

**Comment by bckelley** [comment]
So also i added php_mysqli to the Dockerfile which works fine until you add in the COMPOSE_PROJECT_NAME .env variable 

Edit: Nvr mind this is fixed

**Comment by osteel** [comment]
Does that mean you fixed you Docker Compose version issue?

**Comment by bckelley** [comment]
umm no not really changed the version to 3.6 and commented out the condition: in both php and PMA

**Comment by osteel** [comment]
Did you do this?

> WSL2 isn't Docker though. Please follow the steps listed [here](https://docs.docker.com/desktop/windows/wsl/) and see where you get to

**Comment by osteel** [comment]
Basically, did you try and install the latest version of Docker Desktop

**Comment by bckelley** [comment]
no i hate the docker desktop and refuse to use it when i can use the docker-ce-cli version

**Comment by osteel** [comment]
Look, I'm willing to help but if you're going to ignore my advice it's all a bit pointless. If you insist on not using Docker Desktop, you're going to have to figure out how to update your setup. Please refer to the [documentation](https://docs.docker.com/engine/install/). Closing this now
